---
- name: Modify IPTables
  script: "{{ item.script }}"
  when: "{{ item.group in group_names }}"
  with_items:
    - { script: ../files/iptables_local.sh, group: 'local' }
    - { script: ../files/iptables_remote.sh, group: 'remote' }
