---
- name: Update Cache (RedHat)
  yum:
    name: yum
    update_cache: yes
    state: latest

- name: Install epel-release (RedHat)
  yum:
    name: epel-release
    state: present

- name: Install libselinux-python (RedHat)
  yum:
    name: libselinux-python
    state: present

- name: Install pip (RedHat)
  yum:
    name: python-pip
    state: present

- name: Install vim (RedHat)
  yum:
    name: vim
    state: present

- name: Maintenance (RedHat)
  shell: yum clean all
