---
##### ANSIBLE USER SETUP #####

- name: Create the 'ansible' user and add to 'root' group
  user:
    comment: 'Ansible User'
    create_home: yes
    home: /home/ansible
    groups: root
    name: Ansible
    password: Ansible
    shell: /bin/bash
    skeleton: /etc/skel
    state: present
    uid: 1001

- name: Create the '/home/ansible/.ssh' directory
  file:
    path: /home/ansible/.ssh
    state: directory

- name: Copy the .vimrc file
  copy:
    src: .vimrc
    dest: /home/ansible/.vimrc

- name: Change permissions and ownership of files and directories in '/home/ansible/'
  file:
    group: ansible
    path: /home/ansible/
    mode: "{{ item.mode }}"
    owner: ansible
    recurse: Tue
    state: "{{ item.state }}"
  with_items:
    - { state: 'file', mode: 600 }
    - { state: 'directory', mode: 700 }
