---
- name: Pre-configure commands to save IPTables
  shell: "{{ item }}"
  with_items:
    - "echo iptables-persistent iptables-persistent/autosave_v4 boolean true | sudo debconf-set-selections"
    - "echo iptables-persistent iptables-persistent/autosave_v6 boolean true | sudo debconf-set-selections"

- name: Install IPTables-Persistent
  apt:
    name: iptables-persistent
    state: latest
    update_cache: no
  notify: Repo Maintenance
